import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from '../app/contexts/AuthContext';
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

const AuthProviderClient = dynamic(
  () => import('../app/contexts/AuthContext').then((mod) => mod.AuthProvider),
  { ssr: false }
)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProviderClient>
          {children}
        </AuthProviderClient>
      </body>
    </html>
  );
}